[features]
seeds = false
[programs.localnet]
chicks_staking_locked = "AVauy78yvW2K6QUfUSfPtcxPEaT3V6W1xwGEQQSFDAPC"

[programs.devnet]
chicks_staking_locked = "AVauy78yvW2K6QUfUSfPtcxPEaT3V6W1xwGEQQSFDAPC"

[programs.mainnet]
chicks_staking_locked = "GSA6YFJHtnPFKZUXjVH9uAQdJaPt3bWADDfbeduq9edJ"

[registry]
url = "https://anchor.projectserum.com"

#[provider]
#cluster = "localnet"
#wallet = "/home/bmstart/work/solana/keys/alice.json"

#[provider]
#cluster = "devnet"
#wallet = "/home/bmstart/work/solana/keys/alice.json"

[provider]
cluster = "mainnet"
wallet = "/home/bmstart/work/solana/keys/alice.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
